# Copyright by Intland Software, https://www.intland.com
#
# All rights reserved.
#
# Please note that if you change this docker file, we do not take any responsibility and we are not liable for
# any damage caused through use of this image, be it indirect, special, incidental
# or consequential damages (including but not limited to damages for loss of business, loss of profits, interruption or the like).

version: '3'

services:

  db:
    image: intland/postgres:debian-15.3
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USER=user
      - POSTGRESQL_PASSWORD=pass
      - POSTGRESQL_DATABASE=codebeamer
      - TZ=UTC
    # volumes:
    #   - db-data:/var/lib/postgresql/data
    networks:
      - cb

  app:
    image: intland/codebeamer:2.0.0.0
    ports:
      - 8080:8080
    environment:
      - DEBUG=false
      - TZ=Asia/Shanghai
      - WAIT_HOSTS=db:5432
      - WAIT_HOSTS_TIMEOUT=120
      - "CB_database_JDBC_Username=user"
      - "CB_database_JDBC_Password=pass"
      - "CB_database_JDBC_Driver=org.postgresql.Driver"
      - "CB_database_JDBC_ConnectionURL=jdbc:postgresql://db:5432/codebeamer"
    # volumes:
    #   - app-logo:/home/appuser/codebeamer/repository/config/logo
    #   - app-repository-docs:/home/appuser/codebeamer/repository/docs
    #   - app-repository-search:/home/appuser/codebeamer/repository/search
    #   - app-logs:/home/appuser/codebeamer/logs
    #   - app-tmp:/home/appuser/codebeamer/tomcat/tmp
    networks:
      - cb

networks:
  cb:

# volumes:
#   db-data:
#   app-logo:
#   repository-docs:
#   app-repository-search:
#   app-logs:
#   app-tmp:
