CREATE TABLE "CHANGE_MASTER" 
(	"ID" VARCHAR2(50), 
	"PROJECT" VARCHAR2(255) NOT NULL ENABLE, 
	"BRANCH" VARCHAR2(255) NOT NULL ENABLE, 
	"NUMBER" NUMBER(*,0) NOT NULL ENABLE, 
	"SUBJECT" VARCHAR2(1000), 
	"OWNER" VARCHAR2(255), 
	"FEATURE_GROUP" VARCHAR2(255), 
	"DEPARTMENT" VARCHAR2(255), 
	"CREATED" TIMESTAMP (6), 
	"UPDATED" TIMESTAMP (6), 
	"STATUS" VARCHAR2(255), 
	"INSERTIONS" NUMBER(*,0), 
	"DELETIONS" NUMBER(*,0), 
	"RESOURCE_GROUP" VARCHAR2(255), 
	"TOTAL_COMMENT_COUNT" NUMBER(*,0), 
	"UNRESOLVED_COMMENT_COUNT" NUMBER(*,0), 
	"COMMIT_TYPE" VARCHAR2(255), 
	"ORIGIN_MASTER" CLOB, 
	"ORIGIN_COMMENTS" CLOB, 
	CONSTRAINT "CHANGE_MASTER_PK" PRIMARY KEY ("ID")
);

COMMENT ON TABLE CHANGE_MASTER IS '变更主表';
COMMENT ON COLUMN CHANGE_MASTER.ID IS 'CHANGE ID';
COMMENT ON COLUMN CHANGE_MASTER.PROJECT IS '项目名';
COMMENT ON COLUMN CHANGE_MASTER.BRANCH IS '分支';
COMMENT ON COLUMN CHANGE_MASTER."NUMBER" IS '变更序号';
COMMENT ON COLUMN CHANGE_MASTER.SUBJECT IS '主题';
COMMENT ON COLUMN CHANGE_MASTER.OWNER IS '提交者';
COMMENT ON COLUMN CHANGE_MASTER.FEATURE_GROUP IS '所属特性组';
COMMENT ON COLUMN CHANGE_MASTER.DEPARTMENT IS '所属部门';
COMMENT ON COLUMN CHANGE_MASTER.CREATED IS '创建时间';
COMMENT ON COLUMN CHANGE_MASTER.UPDATED IS '更新时间';
COMMENT ON COLUMN CHANGE_MASTER.STATUS IS '状态';
COMMENT ON COLUMN CHANGE_MASTER.INSERTIONS IS '新增行数';
COMMENT ON COLUMN CHANGE_MASTER.DELETIONS IS '删除行数';
COMMENT ON COLUMN CHANGE_MASTER.RESOURCE_GROUP IS '所属资源组';
COMMENT ON COLUMN CHANGE_MASTER.TOTAL_COMMENT_COUNT IS '提出的问题数量';
COMMENT ON COLUMN CHANGE_MASTER.UNRESOLVED_COMMENT_COUNT IS '未解决问题数量';
COMMENT ON COLUMN CHANGE_MASTER.COMMIT_TYPE IS '提交类型';

CREATE TABLE "CHANGE_COMMENTS" 
(	"ID" VARCHAR2(50), 
	"CHANGE_ID" VARCHAR2(50) NOT NULL ENABLE, 
	"FILE" VARCHAR2(1000), 
	"LINE" NUMBER(*,0), 
	"AUTHOR" VARCHAR2(255), 
	"UPDATED" TIMESTAMP (6), 
	"MESSAGE" VARCHAR2(4000), 
	"TYPE" VARCHAR2(255), 
	"SEVERITY" VARCHAR2(255), 
	"UNRESOLVED" NUMBER(1,0), 
	"IN_REPLY_TO" VARCHAR2(50), 
	CONSTRAINT "CHANGE_COMMENTS_PK" PRIMARY KEY ("ID")
);

COMMENT ON TABLE CHANGE_COMMENTS IS '评审问题';
COMMENT ON COLUMN CHANGE_COMMENTS.ID IS '问题ID';
COMMENT ON COLUMN CHANGE_COMMENTS.CHANGE_ID IS '变更ID';
COMMENT ON COLUMN CHANGE_COMMENTS."FILE" IS '涉及的文件';
COMMENT ON COLUMN CHANGE_COMMENTS.LINE IS '涉及的文件行数';
COMMENT ON COLUMN CHANGE_COMMENTS.AUTHOR IS '问题的提出者';
COMMENT ON COLUMN CHANGE_COMMENTS.UPDATED IS '更新时间';
COMMENT ON COLUMN CHANGE_COMMENTS.MESSAGE IS '问题描述';
COMMENT ON COLUMN CHANGE_COMMENTS."TYPE" IS '问题类型';
COMMENT ON COLUMN CHANGE_COMMENTS.SEVERITY IS '严重程度';
COMMENT ON COLUMN CHANGE_COMMENTS.UNRESOLVED IS '是否未解决';
COMMENT ON COLUMN CHANGE_COMMENTS.IN_REPLY_TO IS '回复';

CREATE TABLE "CHANGE_FILES" 
(	"ID" NUMBER(*,0), 
	"CHANGE_ID" VARCHAR2(50) NOT NULL ENABLE, 
	"FILE" VARCHAR2(1000), 
	"STATUS" VARCHAR2(255), 
	"LINES_INSERTED" NUMBER(*,0), 
	"LINES_DELETED" NUMBER(*,0), 
	"CREATED" TIMESTAMP (6), 
	CONSTRAINT "CHANGE_FILES_PK" PRIMARY KEY ("ID")
);

COMMENT ON TABLE CHANGE_FILES IS '文件';
COMMENT ON COLUMN CHANGE_FILES.ID IS '记录ID';
COMMENT ON COLUMN CHANGE_FILES.CHANGE_ID IS '变更ID';
COMMENT ON COLUMN CHANGE_FILES."FILE" IS '涉及的文件名';
COMMENT ON COLUMN CHANGE_FILES.STATUS IS '操作类型';
COMMENT ON COLUMN CHANGE_FILES.LINES_INSERTED IS '新增行数';
COMMENT ON COLUMN CHANGE_FILES.LINES_DELETED IS '删除行数';
COMMENT ON COLUMN CHANGE_FILES.CREATED IS '操作时间';

CREATE TABLE "LAST_UPDATED_DATETIME" 
(	"ID" VARCHAR2(100), 
	"UPDATED" TIMESTAMP (6), 
	 CONSTRAINT "LAST_UPDATED_DATETIME_PK" PRIMARY KEY ("ID")
);

CREATE SEQUENCE CHANGE_FILES_ID INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER;